openapi: 3.0.0
info:
  title: Example API
  version: "1.0"
servers:
  - url: http://127.0.0.1:8000
paths:
  /message/:
    post:
      summary: Sends a message request
      operationId: sendMessage
      tags:
        - Message
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                persona:
                  type: string
                  example: examplePersona
                uid:
                  type: string
                  example: exampleUID
                message:
                  type: string
                  example: "Health Benefits of Lemons"
                document:
                  type: string
                  example: "LemonPeel/LemmonPeels"
                context:
                  type: string
                  example: "What is the Purpose of this manual?"
                maxTokens:
                  type: integer
                  example: 100
                temperature:
                  type: number
                  format: float
                  example: 0.5
                topP:
                  type: number
                  format: float
                  example: 0.9
                stopSequences:
                  type: array
                  items:
                    type: string
                sessionId:
                  type: string
                  example: exampleUID
                language:
                  type: string
                  example: "en-US"
                requestType:
                  type: string
                  example: "query"
      responses:
        "200":
          description: Request successfully processed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Response message here"
        "401":
          description: Unauthorized access
        "400":
          description: Bad request
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

