#
# Valid Entries
# OpenAI
# OpenAI:gpt-4-0125-preview
# OpenAI:gpt-4-turbo-preview
# DeepInfra
#
# DeepInfra
#DeepInfra:mistralai/Mixtral-8x7B-Instruct-v0.1
#OpenAI Chat
#ChatOpenAI
# ChatOpenAI:gpt-4-0125-preview
# ChatOpenAI:gpt-4-turbo-preview

#Groq
#ChatGroq:mixtral-8x7b-32768
#ChatGroq:llama2-70b-4096
#
#Anthropic
#AnthropicLLM:claude-2.1
#
#Ollma
#Ollama:llama2
default:
  temperature: 0.2
  max_new_tokens: 18000 
  request_timeout: 30
